POST https://node-do-zero-flame.vercel.app/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o video node",
    "duration": 180
}

###
GET https://node-do-zero-flame.vercel.app/videos

###
PUT https://node-do-zero-flame.vercel.app/videos/144245a9-673a-4158-b4ab-e5512f983134
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o video 03",
    "duration": 180
}

###
DELETE https://node-do-zero-flame.vercel.app/videos/144245a9-673a-4158-b4ab-e5512f983134